README.md, bin/pa11y-ci.js, test/integration/cli-sitemap.js
Allow a user to find/replace within sitemap URLs before running Pa11y
tests. Resolves #2.
Sometimes (e.g. with Jekyll) a locally generated sitemap for your site
will include the production URLs. If you want to run Pa11y against a
local copy of the site then you need to find/replace in these URLs.
=> Implement a find/replace for sitemap URLs

bin/pa11y-ci.js, test/integration/cli-sitemap.js, test/integration/mock/website/html/excluded.html, test/integration/mock/website/sitemap.xml
This should allow for simpler use of existing sitemaps rather than requiring pa11y-specific ones; https://github.com/pa11y/ci/issues/10
=> Add command line option: sitemap-exclude

README.md
This also adds extra spacing to match the help output of the CLI.
May be simpler to [review with white space changes ignored](https://github.com/pa11y/ci/pull/19/files?w=1).
=> Fix a typo in the CLI docs

.eslintrc.js, .travis.yml, lib/pa11y-ci.js, package.json, test/integration/cli-erroring.js, test/integration/cli-json.js, test/integration/cli-mixed.js, test/unit/lib/pa11y-ci.js, test/unit/mock/pa11y.mock.js
- Changing node support to version 8 only (breaking change)
- Update to use the pa11y 5 beta version
- Switching to new async/await interface that the new pa11y version makes available
- Updating tests to expect promises not callbacks (and slightly changed results format)
=> Update to use pa11y 5 beta and async/await

README.md, bin/pa11y-ci.js, package.json, test/integration/cli-paths.js
Closes https://github.com/pa11y/pa11y-ci/issues/37.
This will support running as:
```
pa11y-ci '**/*.html' foo/bar.html # quotes so that the globs are interpreted by JS not the shell
```
Added a simple test. Feedback welcome!
=> Add path arg for globbing

bin/pa11y-ci.js, test/integration/cli-config.js
Currently loading JavaScript config files will only work if you left out
the ".js" extension. This is counterintuitive, so I now remove the
extension when we resolve the config file path.
I've tested this with the following:
- The default `.pa11yci` config file with JSON contents
- The default `.pa11yci.js` config file with JS contents
- JSON config without a `.json` extension
- JS config without a `.js` extension
- JSON config with a `.json` extension
- JS config with a `.js` extension
This resolves #39
=> Fix the way configurations are loaded

Makefile, package.json, test/integration/cli-erroring.js, test/integration/cli-json.js, test/integration/cli-mixed.js
Tests are breaking due to a change in Puppeteer's error messaging (GoogleChrome/puppeteer#901) and on my machine an occasional timeout.
=> Update Pa11y version to new 5.0.0 and fix broken tests

.travis.yml
Trying to correct the errors I'm seeing in builds all of a sudden;
```
Error: Failed to launch chrome!
-   [0216/092541.720258:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox!
```
May be related to Travis updates, so I'm trying their recommended fix https://github.com/travis-ci/travis-ci/issues/8836
=> Fix Travis build issues

.eslintrc.js, .pa11yci, .travis.yml, CONTRIBUTING.md, MIGRATION.md, Makefile, README.md, lib/pa11y-ci.js, package-lock.json, package.json, test/integration/cli-erroring.js, test/integration/cli-json.js, test/integration/cli-mixed.js, test/unit/lib/pa11y-ci.js, test/unit/mock/pa11y.mock.js, test/unit/mock/puppeteer.mock.js
This PR contains all the work for Pa11y-ci 2.x which includes:
- Updating Pa11y version to 5.x
- Supporting only Node.js 8+
- Sharing a single browser instance across all tests
All of the code in this PR has been reviewed already in separate PRs.
=> Pa11y-ci 2.x

lib/pa11y-ci.js, test/integration/cli-passing.js, test/integration/mock/config/passing-threshold.json, test/unit/lib/pa11y-ci.js
This enables Pa11y-CI to respect the [Pa11y threshold configuration](https://github.com/pa11y/pa11y#threshold-number) on a per url basis (if provided).
So it will be possible to pass tests even when there are errors present, as long as those errors are fewer than the threshold number given for that url.
No change to the Pa11y-CI `--threshold` flag functionality, which provides a different (aggregate) way to pass tests with errors present.
=> Add check for url threshold config when determining pass/fail

bin/pa11y-ci.js, test/integration/cli-config.js, test/integration/mock/config/extension-js-promise.js
Configs with the extension JS could return a promise rather than the
config object. This is handled by wrapping in a resolving promise
before resolving the fully loaded config.
=> Allow loaded config to return promises

README.md, lib/pa11y-ci.js, package-lock.json, test/integration/cli-json.js, test/unit/lib/pa11y-ci.js
Setting the `useIncognitoBrowserContext` option to true will use Puppeteers `createIncognitoBrowserContext` method to isolate the browser context that tests are ran in. Useful to stop cookies or other headers leaking between tests.
=> Add useIncognitoBrowserContext option for test runs

README.md
=> Fix Typo in Readme, wrong json key name

bin/pa11y-ci.js, lib/pa11y-ci.js, test/unit/lib/pa11y-ci.js
Warnings can be innocuous, but they can also sometimes conceal problems.  This pull request is an effort to ONLY address warnings that had been produced by `eslint` and ultimately not to change any logic or intent within.
=> Minor refactoring to address eslint warnings

CHANGELOG.md, package.json
Please notice this is the 2.3.1 bugfix release of pa11y-ci.
There's been further changes to the main branch of pa11y-ci, which is why this PR is against the `2.3.x` branch.
=> Version 2.3.1

package-lock.json, package.json
This PR replaces the caret (`^`) with the tilde (`~`) selector for dependency versions in order to reduce the potential breakage when updating or integrating with other apps.
It also bumps the dependencies.
=> Allow only bugfix update in dependencies

test/integration/cli-erroring.test.js, test/integration/cli-json.test.js, test/integration/cli-mixed.test.js, test/integration/cli-sitemap.test.js, test/integration/mock/config/erroring-multiple.json, test/integration/mock/config/erroring-single.json, test/integration/mock/config/mixed.json
This PR updates the integrations tests that currently rely on DNS failure by removing that dependency and returning the GitHub Actions tests to a passing state (and fixes #132).  It is based on the example already used for the CLI paths test, but passing an invalid file URL, e.g. `./foo/erroring.html`, results in `ERR_FILE_NOT_FOUND` with no external dependencies.
=> Update integration tests to remove DNS dependencies

package-lock.json, package.json
This commit upgrades pa11y to the latest 5.3.1 version, and downgrades the version of puppeteer used by pa11y-ci from 1.20.0 to 1.19.0 in order to avoid having to download two different versions of puppeteer, as reported in #131.
=> Pin puppeteer version to avoid downloading twice

README.md
We get questions from time to time about running pa11y-ci in Docker (and asking about the `No sandbox` error), we can now point at this!
=> Adds example of running pa11y-ci in Docker

lib/pa11y-ci.js
This is a first attempt at fixing #128. It's unlikely to fix the issue completely, or even at all, as the browser will sometimes crash after testing several URLs and we don't have any logic to reopen a browser that has crashed mid-testing.
=> Retry launching browser once if it fails the first time

MIGRATION.md, README.md, lib/pa11y-ci.js, test/unit/lib/pa11y-ci.test.js
This changes the default for concurrency to 1 (from the previous 2) and the default for useIncognitoBrowserContext to true in order to improve the reliability of pa11y-ci with the default settings.
It also updates the Migration guide to explain these changes.
Closes #147.
=> Change concurrency and incognito mode defaults

bin/pa11y-ci.js, lib/pa11y-ci.js, package-lock.json, package.json
Also fixes indentation issues flagged by the new eslint version, and suppresses the `no-async-promise-executor` error raised by eslint. Dealing with this error is covered by #152.
=> Bump deps to match versions used by pa11y v6

CONTRIBUTING.md, LICENSE, README.md, package.json
I noticed a few urls use http when they could use https. I also updated the license to point to where that URL redirects.
None of this is super necessary, but a small step toward more security seems worthwhile. Might as well use the better protocol from the beginning if possible.
=> use https where possible

lib/pa11y-ci.js
Add missing `await` for closing incognito browser context. Errors have been seen running custom reporters with async functions, as noted in https://github.com/pa11y/pa11y-ci/issues/168#issuecomment-990562886, with the stack trace pointing to this line. The `browserContext.close` function is async, so without the `await` there appears to be timing issues between the [`browserContext.close`](https://github.com/pa11y/pa11y-ci/blob/efad30255318be167c337b6b1b255ad691c0e8b4/lib/pa11y-ci.js#L135) and parent [`browser.close`](https://github.com/pa11y/pa11y-ci/blob/efad30255318be167c337b6b1b255ad691c0e8b4/lib/pa11y-ci.js#L144) (which are likely masked in other cases by pa11y-ci completing and exiting the process).
This change did resolve at least the reporter problem noted in …
=> Add missing await for closing incognito browser context.

.github/workflows/tests.yml, test/integration/cli-json.test.js, test/integration/mock/website/index.js, test/integration/setup.test.js
This PR updates the integration tests to support all platforms, including Windows. The current integration tests fail on Windows for two reasons:
1. The `startWebsite` function and JSON output tests rely on POSIX-style paths, so encounter errors when simply concatenated with Windows paths. The `path.resolve` or `path.join` functions are used instead.
2. The `cliCall` function that executes the tests assumes the `bin` file is executable, which works in *nix systems, but is not true in Windows since it ignores the shebang. This function is updated to explicitly run the `node` command against the `bin` file.
This also adds Windows and Mac test cases to the GitHub Actions, matching https://github.com/pa11y/pa11y/pull/640.
=> Update integration tests to support all platforms, including Windows

README.md
Update README to include additional details and example with JavaScript config file, including how it can be used to dynamically update config. Based on question from https://github.com/pa11y/pa11y-ci/issues/193.
=> Add JavaScript config example to README

.github/workflows/publish.yml, CHANGELOG.md, README.md, package-lock.json, package.json
- Everything in [the changelog entry for `3.1.0`](https://github.com/pa11y/pa11y-ci/pull/226/files?short_path=06572a9#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)
- here's the full diff link for now, since the one in the changelog won't work until the tag `3.1.0` is created: https://github.com/pa11y/pa11y-ci/compare/3.0.1...version-3.1
- Plus items that do not affect the user:
- rename publishing job id to `publish` from `build`
- several dependency updates (minor or patch) from Dependabot
- resolves #176
=> Version `3.1.0`

package.json
The current test scripts single quote the test pattern glob, which runs properly in Linux and macOS, but on Windows it results in no tests found. This then passes since no tests failed, as seen in the following log from [here](https://github.com/pa11y/pa11y-ci/actions/runs/16334292626/job/46143256139).
<details>
<summary>Actions Log</summary>
```
Run npm test
> pa11y-ci@3.1.0 test
> npm run test-coverage && npm run verify-coverage && npm run test-integration
> pa11y-ci@3.1.0 test-coverage
> nyc --reporter=text --reporter=html mocha --file test/unit/setup.test.js 'test/unit/**/*.test.js' --recursive
Warning: Cannot find any files matching pattern "'test/unit/**/*.test.js'"
0 passing (1ms)
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch …
```
=> Fix test script quoting to run properly on Windows

.github/workflows/tests.yml
This PR limits the permissions of the GITHUB_TOKEN for the test/lint Action Workflow to read only. The default permissions for repositories created before February 2023, like this one, is read-write. This resolves two issues identified by CodeQL ([here](https://github.com/pa11y/pa11y-ci/security/code-scanning/5) and [here](https://github.com/pa11y/pa11y-ci/security/code-scanning/6) for those with the appropriate permissions).
=> Set explicit read permissions for tests workflow
